parameters:
- name: subscription
  displayName: subscription
  type: string
  default: Pay-As-You-Go (8b41bb3a-73a0-4041-90c2-d82d4d3cbc5f)
- name: environment
  displayName: environment
  type: string
  default: develop
  values:
  - develop
  - qa1
  - production
trigger: none
pool:
  vmImage: ubuntu-latest

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
- task: TerraformTaskV4@4
  displayName: Run Terraform Init 
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: '-reconfigure'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/${{ parameters.environment }}' 
    backendServiceArm: '${{ parameters.subscription }}'
    backendAzureRmResourceGroupName: 'infra_rg'
    backendAzureRmStorageAccountName: 'infrastanstorageaccount'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'infra-${{ parameters.environment }}-key'
- task: TerraformTaskV4@4
  displayName: Run Terraform Destroy 
  inputs:
    provider: 'azurerm'
    command: 'destroy'
    commandOptions: '-input=false -var "personal_access_token=$(personal_access_token)" -var "client_id=$(client_id)" -var "client_secret=$(client_secret)" -var "tenant_id=$(tenant_id)" -var "subscription_id=$(subscription_id)"'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/${{ parameters.environment }}' 
    environmentServiceNameAzureRM: '${{ parameters.subscription }}'
