apiVersion: v1
kind: Secret
metadata:
  name: namespace-secret
type: Opaque
data:
  # This is azure service bus namespace connection string
  connection: RW5kcG9pbnQ9c2I6Ly9kZXZlbG9wcGlsb3RhcHBzZXJ2aWNlYnVzLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9Um9vdE1hbmFnZVNoYXJlZEFjY2Vzc0tleTtTaGFyZWRBY2Nlc3NLZXk9T2QxREVxamNmUGVaWmZsbXhFaTEzNUVUSksyVnRnaWVaK0FTYk5IamxLYz0=
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
spec:
  secretTargetRef:
    - key: connection
      name: namespace-secret # name of secret
      parameter: connection # key in secret

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pilot-user-service-autoscaling
spec:
  scaleTargetRef:
    name: pilot-user-service
  minReplicaCount: 1
  maxReplicaCount: 4
  pollingInterval: 1
  cooldownPeriod: 5
  triggers:
  - type: azure-servicebus
    metadata:
      subscriptionName: develop_keda_subscription
      namespace: developpilotappservicebus
      topicName: user_topic
      messageCount: "5"
      activationMessageCount: "2"
      cloud: AzurePublicCloud
    authenticationRef:
        name: azure-servicebus-auth