parameters:
  - name: ServiceName
    default: ""
  - name: RunTerraform
    default: False
  - name: subscription
    default: 'Pay-As-You-Go (8b41bb3a-73a0-4041-90c2-d82d4d3cbc5f)'
  - name: RunPostDeploymentTerraform
    default: False 
stages: 
  - stage: Service_Infrastructure_Setup
    displayName: Service Infrastructure Setup
    pool: Azure Pipelines
    condition: eq(${{ parameters.RunTerraform }}, 'True')
    jobs:
      - job: Terraform
        steps:
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        - task: TerraformTaskV4@4
          displayName: Run Terraform Init 
          inputs:
            provider: 'azurerm'
            command: 'init'
            commandOptions: '-reconfigure'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development/predeployment' 
            backendServiceArm: '${{ parameters.subscription }}'
            backendAzureRmResourceGroupName: 'infra_rg'
            backendAzureRmStorageAccountName: 'infrastanstorageaccount'
            backendAzureRmContainerName: 'terraform'
            backendAzureRmKey: '${{ parameters.ServiceName }}.predeployment.terraform.tfstate'
        - task: TerraformTaskV4@4
          displayName: Run Terraform Plan 
          inputs:
            provider: 'azurerm'
            command: 'plan'
            commandOptions: '-input=false -var "client_id=$(client_id)" -var "client_secret=$(client_secret)" -var "tenant_id=$(tenant_id)" -var "subscription_id=$(subscription_id)"'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development/predeployment' 
            environmentServiceNameAzureRM: '${{ parameters.subscription }}'
        - task: TerraformTaskV4@4
          displayName: Run Terraform Apply 
          inputs:
            provider: 'azurerm'
            command: 'apply'
            commandOptions: '-input=false -var "client_id=$(client_id)" -var "client_secret=$(client_secret)" -var "tenant_id=$(tenant_id)" -var "subscription_id=$(subscription_id)"'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development/predeployment' 
            environmentServiceNameAzureRM: '${{ parameters.subscription }}'
        - task: CmdLine@2
          name: SetServicePrincipalVariables
          displayName: Test
          inputs:
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development/predeployment' 
            script: |
                  echo "##vso[task.setvariable variable=servicePrincipalDirectoryVar;isOutput=true]$(terraform output service_sp_tenant_id)"
                  echo "##vso[task.setvariable variable=servicePrincipalIdVar;isOutput=true]$(terraform output service_sp_id)"
                  echo "##vso[task.setvariable variable=servicePrincipalSecretVar;isOutput=true]$(terraform output service_sp_pswd)"
        
  - stage: Deploy
    condition: succeeded()
    variables:
      service_sp_id: $[ stageDependencies.Service_Infrastructure_Setup.Terraform.outputs['SetServicePrincipalVariables.servicePrincipalIdVar'] ]
      service_sp_pswd: $[ stageDependencies.Service_Infrastructure_Setup.Terraform.outputs['SetServicePrincipalVariables.servicePrincipalSecretVar'] ]
      service_sp_tenant_id: $[ stageDependencies.Service_Infrastructure_Setup.Terraform.outputs['SetServicePrincipalVariables.servicePrincipalDirectoryVar'] ]
    displayName: Deploy
    pool: Azure Pipelines
    jobs:
      - job: 
        steps:
        - task: AzureKeyVault@2
          displayName: Get Client Credentials
          inputs:
            azureSubscription: 'pilot-ado-service-connection'
            KeyVaultName: 'develop-pilot-kv'
            SecretsFilter: '*'
        - task: CmdLine@2
          displayName: Check Key Vault
          inputs:
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development/predeployment' 
            script: |
              echo $(service_sp_id)
              echo $(service_sp_pswd)
              echo $(service_sp_tenant_id)
        - task: HelmDeploy@0
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: 'develop_aks_service_endpoint'
            namespace: 'default'
            command: 'upgrade'
            chartType: 'FilePath'
            chartPath: './${{ parameters.ServiceName }}'
            chartVersion: '$(IMAGE_TAG)'
            releaseName: '${{ parameters.ServiceName }}'
            valueFile: './${{ parameters.ServiceName }}/values-develop.yaml'
            arguments: '--atomic'
            overrideValues: 'envValues[1].name=service_sp_id,envValues[1].value=$(service_sp_id),envValues[2].name=service_sp_pswd,envValues[2].value=$(service_sp_pswd),envValues[3].name=service_sp_tenant_id,envValues[3].value=$(service_sp_tenant_id)'

  - stage: Service_Infrastructure_Postdeployment_Setup
    displayName: Service Infrastructure Postdeployment Setup
    pool: Azure Pipelines
    condition: and(eq(${{ parameters.RunPostDeploymentTerraform }}, 'True'), succeeded())
    jobs:
      - job:
        steps:
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        - task: TerraformTaskV4@4
          displayName: Run Terraform Init 
          inputs:
            provider: 'azurerm'
            command: 'init'
            commandOptions: '-reconfigure'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development/postdeployment' 
            backendServiceArm: '${{ parameters.subscription }}'
            backendAzureRmResourceGroupName: 'infra_rg'
            backendAzureRmStorageAccountName: 'infrastanstorageaccount'
            backendAzureRmContainerName: 'terraform'
            backendAzureRmKey: '${{ parameters.ServiceName }}.postdeployment.terraform.tfstate'
        - task: TerraformTaskV4@4
          displayName: Run Terraform Plan 
          inputs:
            provider: 'azurerm'
            command: 'plan'
            commandOptions: '-input=false -var "client_id=$(client_id)" -var "client_secret=$(client_secret)" -var "tenant_id=$(tenant_id)" -var "subscription_id=$(subscription_id)"'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development/postdeployment' 
            environmentServiceNameAzureRM: '${{ parameters.subscription }}'
        - task: TerraformTaskV4@4
          displayName: Run Terraform Apply 
          inputs:
            provider: 'azurerm'
            command: 'apply'
            commandOptions: '-input=false -var "client_id=$(client_id)" -var "client_secret=$(client_secret)" -var "tenant_id=$(tenant_id)" -var "subscription_id=$(subscription_id)"'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development/postdeployment' 
            environmentServiceNameAzureRM: '${{ parameters.subscription }}'