parameters:
  - name: ServiceName
    default: ""
  - name: RunTerraform
    default: False
  - name: subscription
    default: 'Pay-As-You-Go (8b41bb3a-73a0-4041-90c2-d82d4d3cbc5f)'
stages: 
  - stage: Service_Infrastructure_Setup
    displayName: Service Infrastructure Setup
    pool: Azure Pipelines
    condition: eq(${{ parameters.RunTerraform }}, 'True')
    jobs:
      - job:
        steps:
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        - task: TerraformTaskV4@4
          displayName: Run Terraform Init 
          inputs:
            provider: 'azurerm'
            command: 'init'
            commandOptions: '-reconfigure'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development' 
            backendServiceArm: 'Pay-As-You-Go (8b41bb3a-73a0-4041-90c2-d82d4d3cbc5f)'
            backendAzureRmResourceGroupName: 'infra_rg'
            backendAzureRmStorageAccountName: 'infrastanstorageaccount'
            backendAzureRmContainerName: 'terraform'
            backendAzureRmKey: 'ado-develop-key'
        - task: TerraformTaskV4@4
          displayName: Run Terraform Plan 
          inputs:
            provider: 'azurerm'
            command: 'plan'
            commandOptions: '-input=false -var "client_id=$(client_id)" -var "client_secret=$(client_secret)" -var "tenant_id=$(tenant_id)" -var "subscription_id=$(subscription_id)"'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development' 
            environmentServiceNameAzureRM: 'Pay-As-You-Go (8b41bb3a-73a0-4041-90c2-d82d4d3cbc5f)'
        - task: TerraformTaskV4@4
          displayName: Run Terraform Apply 
          inputs:
            provider: 'azurerm'
            command: 'apply'
            commandOptions: '-input=false -var "client_id=$(client_id)" -var "client_secret=$(client_secret)" -var "tenant_id=$(tenant_id)" -var "subscription_id=$(subscription_id)"'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development' 
            environmentServiceNameAzureRM: 'Pay-As-You-Go (8b41bb3a-73a0-4041-90c2-d82d4d3cbc5f)'
  - stage: Deploy
    displayName: Deploy
    pool: Azure Pipelines
    jobs:
      - job: 
        steps:
        - task: HelmDeploy@0
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: 'develop_aks_service_endpoint'
            namespace: 'default'
            command: 'upgrade'
            chartType: 'FilePath'
            chartPath: './${{ parameters.ServiceName }}'
            chartVersion: '$(IMAGE_TAG)'
            releaseName: '${{ parameters.ServiceName }}'
            valueFile: './${{ parameters.ServiceName }}/values-develop.yaml'
            arguments: '--atomic'
     
