parameters:
  - name: ServiceName
    default: ""

stages: 
  - stage: Deploy
    displayName: Deploy
    pool: Azure Pipelines
    jobs:
      - job: 
        steps:
        - task: HelmDeploy@0
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: 'develop_aks_service_endpoint'
            namespace: 'default'
            command: 'upgrade'
            chartType: 'FilePath'
            chartPath: './${{ parameters.ServiceName }}'
            chartVersion: '$(IMAGE_TAG)'
            releaseName: '${{ parameters.ServiceName }}'
            valueFile: './${{ parameters.ServiceName }}/values-develop.yaml'
            arguments: '--atomic'


